In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A.shape

(2, 3)

In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15]])
print(A[1, 2: 4])

[8 9]


In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

B = A[:, 2]
B

array([ 3,  7, 11, 15])

In [ ]:
import numpy as np

A = np.array([[1, 1, 2, 3], 
              [4, 5, 1, 4], 
              [1, 9, 10, 11]])

print(A.sum(axis = 0))

[ 6 15 13 18]


In [ ]:
A = np.array(([1, 2, 3]))
B = np.array([[4, 5, 6]])
print(A + B)

[[5 7 9]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x @ y)

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x * y)

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.dot(x, y))

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.sum(x * y))

32
[ 4 10 18]
32
32


In [ ]:
w = np.zeros(5)
w = w + 2
print(w)

[2. 2. 2. 2. 2.]


In [ ]:
x = np.linspace(-1, 1, 5)
y = 2 * x + 4
print(y)

[2. 3. 4. 5. 6.]


In [ ]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8],[9,10], [11,12]])
print(A@B)

[[ 58  64]
 [139 154]]


In [ ]:
M = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = np.array([1,2,3,4])
M + b

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [ ]:
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
b = np.array([1, 2, 3])
b = np.expand_dims(b, axis = 1)
M + b

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])